export const enSelectors = {
    "lead__title": 'Travel around Russia',
    "lead__subtitle": 'Get a look of the real country',
    'intro__title': 'Best places to visit in Russia',
    'intro__text': 'According to recent surveys, 95% of Russians want to travel abroad and only 36% are going to spend their next vacation in Russia. They think they have already seen everything in their country. Actually there are a lot of places to visit in Russia - forests, seashores, rivers. It will not take you a lot of money or time to travel around Russia. For example, Vera Bashmakova - a young mother of 3 chidlren drove 20 000 km exporing Russia with her children. This web-site will tell you about amazing places that you can must visit in our beautiful country.',
    'intro__span_one': 'Time zones',
    'intro__span_two': 'UNESCO natural heritage sites',
    'intro__span_three': 'UNESCO cultural heritage sites',
    'intro__span_four': 'Nature reserves',
    'intro__span_five': 'Airports',
    'place__titleOne': 'Curonian Spit',
    'place__paragraphOne': 'In the middle of forests and sand dunes, you can see two water horizons — the calm Curonian lagoon on one side and the rippling waves of the Baltic sea on the other. It is a unique natural area on the edge of the Russian enclave.',
    'place__paragraphTwo': 'This is not the end of the Kaliningrad region. For the traveler and explorer, there is also the westernmost point of Russia, the Baltic spit, and the German heritage of a scattering of small seaside towns. The atmosphere of these places excludes fuss, dipping into the tranquility of nature and the smell of the steel, cool sea.',
    'place__titleTwo': 'Kola Peninsula',
    'place__paragraphThree': 'Almost the entire Peninsula is located above the Arctic circle. The Sami tundra, from which to the South — the taiga and the North-Arctic ocean, pretending to be the Barents sea.',
    'place__paragraphFour': "You may have watched Zvyagintsev and even heard the story of the Arctic festival in Teriberka. Perhaps you may also recall the word 'Khibiny'. You may not be interested in the ultra-deep borehole that penetrates the earth's crust, and apatites may seem boring to you. But your dream to see the Northern lights begins to come true with a ticket to Murmansk.",
    'place__titleThree': 'Altai',
    'place__paragraphFive': 'Altai is one of the most beautiful places in Russia. First of all, because of the mountains: if you go along the ridge, you will see slopes dotted with pine trees, mountain rivers and lakes. And if you open the car window, you can get acquainted with the invisible miracle of these places-the mountain air.',
    'place__paragraphSix': 'The climate of Altai is moderate, so it is best to go here in the summer. This way you will see all the variety of local flora and fauna. Moose roam the forests of Altai, eagles fly over the ridges, and ROE deer graze on the plains. And the famous manuls are also inhabitants of the Altai territory.',
    'place__titleFour': 'Winter Baikal',
    'place__paragraphSeven': 'Everyone knows Baikal as the largest lake in the world. Many people also know that this is the largest source of fresh water and one of the most beautiful places in Russia.',
    'place__paragraphEight': 'Of course, this is true. But the lake is ideal for skijoring competitions. This is a sport where a skier ties himself to a motorcycle, and the tandem tries to develop as much speed as possible on the ice. In March 2019, the Baikal mile festival set a world record of 197.011 km/h.',
    'place__titleFive': 'Karelia',
    'place__paragraphNine': "Siberia does not end in the Urals, but in Karelia: the Siberian larch that forms the taiga does not grow West of the Vodlozer. But here it grows up to 30 meters — the forests of Karelian national parks have never known an axe because of impassable swamps. Some pines are more than half a Millennium old. Touch a living being who saw the sun before Ivan the terrible saw it. You can't find a trail for a hundred kilometers in a virgin forest. And on rare paths, trees a few meters from the ground are marked with bear claws. So that everyone knows who is the boss.",
    'cover__title': 'Get to Baikal «on the dogs»',
    'cover__subtitle': 'How to get to Baikal from the capital by train',
    'footer__linkMap': 'Map',
    'footer__linkWeather': 'Weather',
    'footer__linkTimetable': 'Timetable',
    'footer__linkCalendar': 'Calendar',
    'footer__linkTravel': 'Travel',
    'lead__caption': "you've got the best train seat!",
}

export const ruSelectors = {
    "lead__title": 'Путешествия по России',
    "lead__subtitle": ' Настоящая страна не в выпусках новостей, а здесь.',
    'intro__title': 'Чего мы там не видели?',
    'intro__text': 'По опросам ВЦИОМ, 95% россиян мечтают куда-нибудь поехать, но только 36% планируют провести отпуск в родной стране. Мол, чего мы тут, дома, не видели? На самом деле, Россия — это целая вселенная с ласковым морем юга, густыми лесами Саян и суровыми льдами плато Путорана. А ещё увидеть все эти красоты можно без миллионов на счету, загранпаспорта и многочасовых перелетов. Как, например, Вера Башмакова — смелая молодая мама, которая взяла в охапку троих детей, усадила их в свою «Ладу» и проехала 20 тысяч километров по родной стране. Мы выбрали и описали некоторые интересные места, достойные вашего отпуска.',
    'intro__span_one': 'Часовых поясов',
    'intro__span_two': 'Объектов природного наследия ЮНЕСКО',
    'intro__span_three': 'Объектов культурного наследия ЮНЕСКО',
    'intro__span_four': 'Природных заповедников',
    'intro__span_five': 'Аэропортов',
    'place__titleOne': 'Куршская коса',
    'place__paragraphOne': 'Здесь, посреди лесов и песчаных дюн, вы сможете увидеть два водных горизонта — спокойного Куршского залива с одной стороны и подёрнутого рябью волн Балтийского моря с другой. Уникальная природная зона на краю российского анклава.',
    'place__paragraphTwo': 'На этом Калининградская область не заканчивается. Для путешественника и исследователя там же по соседству — самая западная точка России, Балтийская коса, — и немецкое наследие россыпи небольших приморских городов. Атмосфера здешних мест исключает суету, окуная в спокойствие природы и запах стального, прохладного моря.',
    'place__titleTwo': 'Кольский',
    'place__paragraphThree': 'Почти весь полуостров находится за Полярным кругом. Саамская тундра, от которой на юг — тайга, а на север — Ледовитый океан, прикидывающийся Баренцевым морем.',
    'place__paragraphFour': 'Возможно, вы смотрели Звягинцева и даже слышали историю арктического фестиваля в Териберке. Возможно, слово «Хибины» не осталось под снегом школьных воспоминаний об уроках географии. Возможно, вы не интересовались пронизывающей земную кору сверхглубокой скважиной, а от апатитов вас давно накрывает апатия. Но ваша мечта увидеть северное сияние начинает сбываться с билетом в Мурманск.',
    'place__titleThree': 'Алтай',
    'place__paragraphFive': 'Алтай — одно из красивейших мест в России. В первую очередь из-за гор: если ехать вдоль хребта, вы увидите склоны, усыпанные соснами, горные реки и озёра. А если вы откроете в автомобиле окна, сможете познакомиться с невидимым чудом здешних мест — горным воздухом.',
    'place__paragraphSix': 'Климат на Алтае умеренный, поэтому ехать сюда лучше всего летом. Так вы увидите всё разнообразие местной флоры и фауны. По лесам Алтая бродят лоси, над хребтами летают орлы, а на равнинах пасутся косули. И знаменитые манулы — тоже обитатели Алтайского края.',
    'place__titleFour': 'Зимний Байкал',
    'place__paragraphSeven': 'Всем известен Байкал как крупнейшее озеро в мире. Многие также знают, что это самый большой источник пресной воды и одно из красивейших мест в России.',
    'place__paragraphEight': 'Конечно, это всё так. Но Байкал ещё идеальное место для соревнований по скийорингу. Это такой вид спорта, когда лыжник привязывает себя к мотоциклу, и тандем старается развить как можно бóльшую скорость на льду. В марте 2019 года на фестивале «Байкальская миля» был поставлен мировой рекорд — 197.011 км/ч.',
    'place__titleFive': 'Карелия',
    'place__paragraphNine': 'Сибирь заканчивается не на Урале, а в Карелии: образующая тайгу сибирская лиственница не растёт западнее Водлозера. Зато здесь она вымахивает на 30 метров — леса карельских национальных парков из-за непроходимых болот никогда не знали топора. Некоторым соснам уже больше чем полтысячелетия. Прикоснитесь к живому существу, видевшему солнце раньше, чем увидал его Иван Грозный. В девственном лесу на сотню километров не встретишь тропы. А на редких тропинках деревья в паре метров от земли помечены медвежьими когтями. Чтобы все знали, кто тут хозяин.',
    'cover__title': 'До Байкала «на собаках»',
    'cover__subtitle': 'Путешествие от столицы до Байкала на электричках.',
    'footer__linkMap': 'Карты',
    'footer__linkWeather': 'Погода',
    'footer__linkTimetable': 'Расписание',
    'footer__linkCalendar': 'Календарь',
    'footer__linkTravel': 'Путешествия',
    'lead__caption': 'ваша полка — верхняя',
}